### ISSUE TITLE
Add Network Configuration for Multiple Networks

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria-cli-go#70] opened 2024-05-02 00:00 UTC
Currently, the `chain_id` for all sequencer networks is hard coded to `astria-dusk-5` within the generated config from the cli. To allow the cli to work with any of Astria's networks, more sophisticated configuration options are required.

For example, having a config file like so:
```
[networks.local]
sequencer.chain_id = "sequencer-test-chain-0"
sequencer.grpc = "http://127.0.0.1:8080/"
sequencer.rpc = "http://127.0.0.1:26657/"

[networks.dusk]
sequencer.chain_id = "astria-dusk-5"
sequencer.grpc = "https://grpc.sequencer.dusk-5.devnet.astria.org/"
sequencer.rpc = "https://rpc.sequencer.dusk-5.devnet.astria.org/"
```
A `--chain-id` flag could also be added to `astria-go dev init` to configure the local sequencers chain id. 

Adding this feature may also change the current `--local` and `--remote` run flags to use flags that represent that types of network.
`--local` -> local sequencer
`--dusk` -> remote dev net
etc.

**Comment by steezeburger** [comment] 2024-05-02 19:44
I had accidentally created a duplicate of this. Just leaving my notes from that issue here for posterity:

We want some kind of hierarchical configuration to make it easier for both the user to change values and make it easier for us as the cli developers to programmatically change config values.

The main goal of something like a `--network` flag would be to make it easier to support the following workflow:

1. spin up local sequencer + rollup
2. spin up local rollup hitting a remote testnet sequencer
3. spin up local rollup hitting a remote prodnet sequencer

**Closed** 2024-05-23 20:28 UTC
